### ISSUE TITLE
concurrent API requests for OpenAI Spec results in inconsistent results

### ISSUE THREAD

**Issue by aniketmaurya** [Lightning-AI/LitServe#106]
If client A and B hit the server concurrently, client B gets the response for the request provided by client A.

```
client A -> Request("What is the color of sky?")
client B -> Request("What is the color of apple?")
```

`server.dispose_pipe()` recycles the pipes and client B gets the same `Pipe` object back. 

Also, it seems like [Connections](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.connection.Connection.close) are closed automatically when garbage collected and we can call the `close()` method to close it manually.

cc: @lantiga

**Comment by lantiga** [comment]
Ugh, good find
