### ISSUE TITLE
Feature: Add support to include tools for OpenAI Chat Template to enable function calling.

### ISSUE THREAD

**Issue by bhimrazy** [Lightning-AI/LitServe#117]
### Description

Introduce support for integrating tools in chat messages, similar to the [OpenAI GPT-4 function calling](https://platform.openai.com/docs/guides/function-calling). This feature would enable users to include tools in their chat interactions, allowing the model to return specific function based on user queries.

Example usage:

```json
{
  "model": "lit",
  "messages": [
    {
      "role": "user",
      "content": "What's the weather like in Boston today?"
    }
  ],
  "tools": [
    {
      "type": "function",
      "function": {
        "name": "get_current_weather",
        "description": "Get the current weather in a given location",
        "parameters": {
          "type": "object",
          "properties": {
            "location": {
              "type": "string",
              "description": "The city and state, e.g. San Francisco, CA"
            },
            "unit": {
              "type": "string",
              "enum": ["celsius", "fahrenheit"]
            }
          },
          "required": ["location"]
        }
      }
    }
  ],
  "tool_choice": "auto"
}
```

This proposal also includes adding options for `Tool Message` in messages and `tool_calls` in the assistant message.

### Additional Context

This feature would streamline the implementation of chat generation APIs with function calling support, aligning with OpenAI's specifications and benefiting users seeking more interactive and functional chat applications.

**Comment by bhimrazy** [comment]
Hi @williamFalcon,

Please let me know how you feel about this feature, and then I can proceed accordingly.
Thank you!

**Comment by aniketmaurya** [comment]
hey @bhimrazy, sounds great!! Feel free to create a PR and we will help you finish merge it. 😄

**Comment by bhimrazy** [comment]
> hey @bhimrazy, sounds great!! Feel free to create a PR and we will help you finish and merge it. 😄

Sure, Thank you @aniketmaurya
