### ISSUE TITLE
Question: Serving LLama3-70B on multiple GPUs

### ISSUE THREAD

**Issue by BZandi** [Lightning-AI/LitServe#120]
I would like to serve the `Meta-Llama-3-70B-Instruct` model using LitServe with 2xA100 GPUs. However, I am having trouble understanding how to proceed.

Is it feasible to use the provided [LLama-8B-example](https://lightning.ai/lightning-ai/studios/deploy-a-private-llama-3-8b-api) by simply changing the checkpoint directory and the number of GPUs used?

Or do I need to reorganize the code provided in the [sequentially.py](https://github.com/Lightning-AI/litgpt/blob/main/litgpt/generate/sequentially.py) file from LitGPT to match the structure used in LitServe?

**Comment by aniketmaurya** [comment]
hi @BZandi, you can set the `devices=2` (number of GPUs) in the `LitServer` class and it will serve Llama on two processes. Note that, here the model will be replicated on two GPUs and not share parameters (no distributed inference). 

Following is the updated code to serve Llama 8B on two GPUs:

```py
import pathlib, torch, os
from litgpt.generate.base import generate
import litgpt as gpt
import lightning as L
import litserve as ls


class SimpleLitAPI(ls.LitAPI):
    def __init__(self, checkpoint_dir, max_new_tokens=50):
        super().__init__()
        self.checkpoint_dir = pathlib.Path(checkpoint_dir)
        self.max_new_tokens = max_new_tokens

    def setup(self, device):
        config = gpt.config.Config.from_file(self.checkpoint_dir / "model_config.yaml")
        device = torch.device(device)
        torch.set_float32_matmul_precision("high")

        fabric = L.Fabric(
            accelerator=device.type, 
            devices=1 if device.type=="cpu" else [device.index], 
            precision=gpt.utils.get_default_supported_precision(training=False)
        )
        
        self.tokenizer = gpt.tokenizer.Tokenizer(self.checkpoint_dir)
        self.prompt_style = gpt.prompts.PromptStyle.from_config(config)
        with fabric.init_module(empty_init=True):
            model = gpt.model.GPT(config)
        with fabric.init_tensor():
            model.set_kv_cache(batch_size=1)
        model.eval()

        self.model = fabric.setup_module(model)
        gpt.utils.load_checkpoint(fabric, self.model, self.checkpoint_dir / "lit_model.pth")
        self.device = fabric.device
        print('setup complete...')

    def decode_request(self, request):
        prompt = request["prompt"]
        prompt = self.prompt_style.apply(prompt)
        encoded = self.tokenizer.encode(prompt, device=self.device)
        return encoded

    def predict(self, inputs):
        prompt_length = inputs.size(0)
        max_returned_tokens = prompt_length + self.max_new_tokens

        y = generate(self.model, inputs, max_returned_tokens, temperature=0.8, top_k=200, top_p=1.0, eos_id=self.tokenizer.eos_id)

        for block in self.model.transformer.h:
            block.attn.kv_cache.reset_parameters()
        return y

    def encode_response(self, output):
        decoded_output = self.tokenizer.decode(output)
        return {"output": decoded_output}

def run_server():
    checkpoint_dir = os.getcwd() + '/checkpoints/meta-llama/Meta-Llama-3-8B-Instruct'
    api = SimpleLitAPI(checkpoint_dir=checkpoint_dir, max_new_tokens=50)
    server = ls.LitServer(api, devices=2)
    server.run(port=8000)

if __name__ == '__main__':
    run_server()
```

**Comment by aniketmaurya** [comment]
generally with distributed inference for large models like a 70B LLM, the parameters would be split across multiple GPUs. It means you will have a single LLM being served over multiple GPUs to accommodate the large model size.

Specifically for LitGPT's [sequentially.py](https://github.com/Lightning-AI/litgpt/blob/main/litgpt/generate/sequentially.py), I think @rasbt would be able to explain the best.

**Comment by lantiga** [comment]
Hey @BZandi, `sequentially.py` is like pipeline parallelism: you place different blocks on different devices and you execute the computation across devices. It's not particularly optimized but it gets the job done.

Note that this is fully orthogonal to litserve and can be totally used with it: you can still initialize a model to work `sequentially` in the `setup` of `LitServer`, and any call to it will span across devices.

The only minor caveat is that in `setup` you receive a `device` argument for convenience, but you'll want to probably hard-code the devices in `setup` when initializing the model.
