### ISSUE TITLE
OpenAI spec non-streaming response contains multiple `space` tokens

### ISSUE THREAD

**Issue by aniketmaurya** [Lightning-AI/LitServe#128]
While serving a Llama-3 8B instruct LLM using OpenAI spec, the endpoint returns multiple spaces between words. It is because Llama generates contains space in the generated token. 

We should use empty string to concat [OpenAI non-streaming chat content](https://github.com/Lightning-AI/LitServe/blob/81fffb66c6b8a95562317943e7de77dc1f2a5faf/src/litserve/specs/openai.py#L359-L364)

```
for i, streaming_response in enumerate(pipe_responses):
            msgs = []
            tool_calls = None
            async for chat_msg in streaming_response:
                chat_msg = json.loads(chat_msg)
                logger.debug(chat_msg)
                chat_msg = ChatMessage(**chat_msg)
                msgs.append(chat_msg.content)
                if chat_msg.tool_calls:
                    tool_calls = chat_msg.tool_calls

            # Is " " correct choice to concat with?
            content = " ".join(msgs)
            msg = {"role": "assistant", "content": content, "tool_calls": tool_calls}
```

here is the llama response:
<img width="543" alt="image" src="https://github.com/Lightning-AI/LitServe/assets/21018714/bc5c7c67-8f7a-4a98-a59b-0bcb29347df5">

**Comment by bhimrazy** [comment]
Thank you @aniketmaurya for opening this issue. 

When utilizing function calls, I encountered a similar issue where the content was expected to be an empty string, but instead, it returned a string filled with white spaces due to the usage of `" ".join(msgs)`.

```json
{
  "role": "assistant",
  "content": "                                  ",
  "name": null,
  "tool_calls": [
    {
      "id": "ANgPNjQuK",
      "type": "function",
      "function": {
        "name": "get_current_weather",
        "arguments": "{\"location\": \"Paris\", \"unit\": \"celsius\"}"
      }
    }
  ],
  "tool_call_id": null
}

```

**Comment by bhimrazy** [comment]
I agree with using empty string to concat.
What do you think @lantiga?
