### ISSUE TITLE
document better

### ISSUE THREAD

**Issue by DanTaranis** [Lightning-AI/LitServe#129]
Hey - the documentation is super minimal.
I'm trying to pass a batch and it's just not working. 
please show a minimal working example or something.

**Comment by aniketmaurya** [comment]
hi @DanTaranis, thank you for the feedback. we are working on the documentation and will launch the updated documentation soon. 

In the meanwhile, to serve a model with dynamic batching, you would need to provide `max_batch_size` argument that specifies the maximum number of items in a batch that your model can handle. 

Here is a toy example:

```
import numpy as np
import litserve as ls

class SimpleBatchedAPI(ls.LitAPI):
    def setup(self, device) -> None:
        self.model = lambda x: x ** 2

    def decode_request(self, request):
        return np.asarray(request["input"])

    def predict(self, x):
        result = self.model(x)  # model will process a numpy array of dimension=4
        return result

    def encode_response(self, output):
        return {"output": output}

if __name__ == "__main__":
    api = SimpleBatchedAPI()
    server = ls.LitServer(api, max_batch_size=4, batch_timeout=0.05)
    server.run(port=8000)
```

Note that if your decode_request returns a data type which is NOT NumPy or a PyTorch Tensor then you will have to define `batch` and `unbatch` which basically convert a list of inputs to a batched data that is supported by your model.

**Comment by DanTaranis** [comment]
oops - I completely missed the batch unbatch section. thanks
