### ISSUE TITLE
CI issues

### ISSUE THREAD

**Issue by rasbt** [Lightning-AI/LitServe#130]
What is this triaging error?

<img width="961" alt="Screenshot 2024-06-05 at 10 18 19 AM" src="https://github.com/Lightning-AI/LitServe/assets/5618407/eaf63a4f-84bb-451b-aafb-02c70e9ccddf">

https://github.com/Lightning-AI/LitServe/actions/runs/9386690667/job/25847870822

Can we remove or fix this @aniketmaurya ?

**Comment by Borda** [comment]
let's drop it for now as here are almost no PRs at all and use mergify if needed for future... d971311b49e9b89df1dd92d82166b5f079a4c60e

**Comment by rasbt** [comment]
Thanks @Borda !
