### ISSUE TITLE
Add health check endpoint

### ISSUE THREAD

**Issue by aniketmaurya** [Lightning-AI/LitServe#181]

**Comment by bhimrazy** [comment]
Hi @aniketmaurya,

I wanted to check if the health check endpoint you're suggesting is intended to send a simple `ok` status response or something more detailed like the example below:

**Endpoint:** `/health`

**Response Structure:**
```json
{
  "status": "ok",
  "version": "1.2.3",
  "description": "LitServe Health Check",
  "checks": [
    {
      "name": "uptime",
      "status": "pass",
      "observedValue": 3600.5,
      "observedUnit": "seconds"
    },
    {
      "name": "cpu_usage",
      "status": "pass",
      "observedValue": 45.2,
      "observedUnit": "percent"
    },
    {
      "name": "memory_usage",
      "status": "warn",
      "observedValue": 82.7,
      "observedUnit": "percent",
      "output": "Memory usage is above 80% 🟡"
    },
    {
      "name": "disk_usage",
      "status": "pass",
      "observedValue": 68.3,
      "observedUnit": "percent"
    }
  ],
  "timestamp": "2024-07-25T14:30:15.123Z"
}
```

I would be happy to contribute to this issue.😊
Thank you!

**Comment by aniketmaurya** [comment]
hey @bhimrazy , sorry for late reply! I was thinking to add an endpoint which just returns either `ok` or `not ready` with right http status code in the first version. 

`Not ready` means that LitServe hasn't completed the `LitAPI.setup` step in the parallel worker process and `ok` means everything is ready and LitServe is ready to serve.

**Comment by bhimrazy** [comment]
Hi @aniketmaurya , 
Thanks for your response and clarification! 

 I'll start working on a PR for this and we can continue our discussion on the PR to refine the implementation.😊

**Comment by aniketmaurya** [comment]
Great @bhimrazy! lmk if you need any help, we can get on a quick call.
