### ISSUE TITLE
move `wrap_litserve_start` to utils

### ISSUE THREAD

**Issue by aniketmaurya** [Lightning-AI/LitServe#195]
> I would rather reserve `conftest` for fixtures and this (seems to be) general functionality move to another utils module

_Originally posted by @Borda in https://github.com/Lightning-AI/LitServe/pull/190#discussion_r1705957686_

**Comment by ankitsharma07** [comment]
hey i would like to take this up..

**Comment by aniketmaurya** [comment]
feel free to go ahead @ankitsharma07 🚀

**Comment by ankitsharma07** [comment]
> feel free to go ahead @ankitsharma07 🚀 

thanks.

**Comment by aniketmaurya** [comment]
@ankitsharma07 let me know if you need any help.

**Comment by ankitsharma07** [comment]
@aniketmaurya you can close this one
