### ISSUE TITLE
Add support for `response_format` in OpenAI Spec

### ISSUE THREAD

**Issue by bhimrazy** [Lightning-AI/LitServe#196]
## 🚀 Feature
Add support for `response_format` in OpenAI Spec

### Motivation
- [Structured Outputs](https://openai.com/index/introducing-structured-outputs-in-the-api/)

**Comment by bhimrazy** [comment]
I would be happy to contribute to this feature.

**Comment by aniketmaurya** [comment]
Thanks for creating the issue @bhimrazy! please feel free to go ahead 🚀
