### ISSUE TITLE
Decorator design for `LitServer`

### ISSUE THREAD

**Issue by baggiponte** [Lightning-AI/LitServe#218]
Hello there! Great release. Just dropping in to suggest a stylistic refactor. Let me know what you think 😄 

## 🚀 Feature

Provide a decorator/pythonic pattern to instantiate your API Server.

### Motivation

Mostly aesthetics, readability and comfort.

### Pitch

Now:

```python
import litserve as ls

class MyAPI(ls.LitAPI):
	...

if __name__ == "__main__": 
	server = ls.LitServer(MyAPI(), ...)
```

The proposal

```python
import litserve as ls

@ls.server(accelerator="auto", max_batch_size=1, ...)
class MyAPI(ls.LitAPI):
    ...
```

Advantages:

* keeps configurations coupled to the service.
* A bit more pythonic/less typing
* You don't need to rewrite a lot of code: the decorator basically does `server = ls.LitServer(MyAPI(), ...)` and returns it for you.
* You could go as far as even dropping the fact that `MyAPI` needs to inherit from `LitAPI`, because the decorator logic could handle the validation (say: `LitServer.from_api(...)`). I guess that using an ABC also provides you with static analysis (e.g. "you did not implement X").
* this plays along well with uvicorn, since you can launch a server from a function returning one using `--application-factory=...` ([ref](https://www.uvicorn.org/#application-factories)).

Cons:

* Two ways of doing the same thing, I guess?

**Comment by williamFalcon** [comment]
we’re not interested in decorators but appreciate the suggestion. 

our API has been very carefully designed and already considered these options.
