### ISSUE TITLE
May I ask if it is possible to deploy complex pipelines such as ControlNet and IP Adapter in Stable Diffusion? Do you have any examples

### ISSUE THREAD

**Issue by libai-lab** [Lightning-AI/LitServe#236]
May I ask if it is possible to deploy complex pipelines such as ControlNet and IP Adapter in Stable Diffusion? Do you have any examples？

**Comment by williamFalcon** [comment]
Built it in about 15 minutes...
https://lightning.ai/lightning-ai/studios/deploy-a-controlled-image-generation-api-controlnet

**Comment by libai-lab** [comment]
> Built it in about 15 minutes... @libai-lab https://lightning.ai/lightning-ai/studios/deploy-a-controlled-image-generation-api-controlnet

https://lightning.ai/mpilosov/studios/stable-diffusion-with-comfyui?section=featured&query=comfy ,Based on this example of Comfyui, can we deploy Comfyui as a backend API for mobile users to use？

**Comment by aniketmaurya** [comment]
@libai-lab haven't really checked comfy-ui but you should be able to deploy any kind of Python application or model that can be loaded in Python with LitServe.

**Comment by aniketmaurya** [comment]
Closing the issue since it has been answered. Please feel free to reopen if still got questions.

**Comment by martintomov** [comment]
@libai-lab did you manage to deploy comfyui as api on litserve? I looked at the stable diffusion example by @williamFalcon, and also some community studio templates
