### ISSUE TITLE
Create Makefile to run common development tasks locally

### ISSUE THREAD

**Issue by AdolfoVillalobos** [Lightning-AI/LitServe#237]
## 🚀 Feature

Hi! I just found this project. Really cool!

I wanted to propose a feature to create a `Makefile` in the repo.

The objective is to simplify local development and contribution by creating a `Makefile` that encapsulates and standardizes common development tasks such as running tests, building docs, etc. It is inspired by pydantic's Makefile: 

https://github.com/pydantic/pydantic/blob/main/Makefile

I would be happy to contribute. 

A first stab at the problem would be to create a `Makefile` to run the following tasks:

- Install dependencies `make install`
- Run tests: `make test`
- Run linter/formater: `make lint` / `make format`

In the future, other checks could be run and integrated to the CI:
- Run benchmarks
- Run mypy.
- etc.

### Motivation

The motivation is to provide a toolkit for developers in order to simplify the process of contributing to this cool project

### Pitch

Add a Makefile to run common development tasks locally.

**Comment by aniketmaurya** [comment]
hi @AdolfoVillalobos, really appreciate the suggestion. At this moment, we only have tests that can be used with Makefile, docs live on our platform [here](https://lightning.ai/docs/litserve/home). So, it would be an overkill for test.

**Comment by AdolfoVillalobos** [comment]
Fair enough! I will be looking at other ways to contribute. Cheers!
