### ISSUE TITLE
Replace uvicorn server with gunicorn

### ISSUE THREAD

**Issue by vrdn-23** [Lightning-AI/LitServe#243]
## 🚀 Feature

Is there a particular reason why LiTServe has not considered moving the app server to [gunicorn](https://gunicorn.org) instead of uvicorn? 

### Motivation

Uvicorn doesn't do process management and is not recommended to be used for production-grade systems ([as mentioned in the uvicorn documentation itself](https://www.uvicorn.org/#running-with-gunicorn)).

### Pitch

Replace the uvicorn server in [server.py](https://github.com/Lightning-AI/LitServe/blob/9b974bb3dc0053ccf1aa7bcf40896e7bc72b23f4/src/litserve/server.py#L752) with a gunicorn server

**Comment by aniketmaurya** [comment]
gunicorn is a process manager when used with uvicorn. We don't need it here as LitServer acts like a process manager here. Also, uvicorn has its own process manager now so we will keep it lean.

https://www.uvicorn.org/deployment/#using-a-process-manager
