### ISSUE TITLE
504 gateway timeouts

### ISSUE THREAD

**Issue by grumpyp** [Lightning-AI/litserve#26]
Hi guys,

using one GPU works better than working with 4 GUPs e.g.
I am running it on LightningAI and not even one request goes through at all if running on 4 devices.

`server = LitServer(SimpleLitAPI(), accelerator="cuda", devices=1, timeout=60)`

vs

`server = LitServer(SimpleLitAPI(), accelerator="cuda", devices=4, timeout=60)`

Any hint?

**Comment by lantiga** [comment]
This has regressed with the last changes. @aniketmaurya can you bisect?

**Comment by aniketmaurya** [comment]
hi @grumpyp, thank you for reporting. I am not able to reproduce this issue. Could you provide a reproducible example or maybe we can connect over a quick call to debug this quickly?

**Comment by grumpyp** [comment]
@aniketmaurya would love to hop on a call yes. I am on your Discord - same username - feel free to ping me once you're available. Appreciate your help!

**Comment by aniketmaurya** [comment]
thank you @grumpyp! DM'd you on Discord.
