### ISSUE TITLE
Setup step is not awaited

### ISSUE THREAD

**Issue by andreieuganox** [Lightning-AI/LitServe#263]
## 🐛 Bug

The `setup` step doesn't wait for all the defined processes to finish. This means that the application is declared working, even though the model is still not loaded. 

### To Reproduce

Please take a look at the code sample below.

#### Code sample

```
import litserve as ls
from gliner import GLiNER

# (STEP 1) - DEFINE THE API
class SimpleLitAPI(ls.LitAPI):
    def setup(self, device):
        # setup is called once at startup. Build a compound AI system (1+ models), connect DBs, load data, etc...
        self.model = GLiNER.from_pretrained("urchade/gliner_mediumv2.1")
```

Logs:
```
sp-gliner-api-v1  | INFO:     Started server process [31]
sp-gliner-api-v1  | INFO:     Waiting for application startup.
sp-gliner-api-v1  | INFO:     Application startup complete.
sp-gliner-api-v1  | uvloop is not installed. Falling back to the default asyncio event loop.
Fetching 5 files: 100%|██████████| 5/5 [00:00<00:00, 17832.93it/s]
sp-gliner-api-v1  | /usr/local/lib/python3.9/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
....
```

### Expected behavior

`Application startup complete` should be triggered after the model is loaded. 

### Environment
Local / Docker

**Comment by bhimrazy** [comment]
Hi @andreieuganox,

I think the application startup complete (logged from uvicorn) might be separate from the setup phase. If we wait for the model to load completely, it logs the setup completion for the specific worker afterward.

![image](https://github.com/user-attachments/assets/a650d412-79a5-4bae-b880-f0f7e0668c70)

https://lightning.ai/docs/litserve/features/full-control#health-check

**Comment by AdolfoVillalobos** [comment]
I just have a few thoughts on the backend implementation, which is quite interesting.

It seems there are 2 primary sets of processes in the application:

- One to host the FastAPI servers (uvicorn server, actually)
- One or more destined to handle the requests/workload, depending on the number of processors.

Although the FastAPI might be ready to receive requests, the workers are still not yet ready to consume those requests and generate responses.

I'm not sure those processes can always be easily synchronized to ensure the workers are ready before the Uvicorn server.

**Comment by aniketmaurya** [comment]
yes, as mentioned by @bhimrazy, you can check if the server has started or not using the `/health` endpoint.
