### ISSUE TITLE
If `workers_per_device` is set to 1, how can I set a model instance to be able to concurrency?

### ISSUE THREAD

**Issue by ALEXuH** [Lightning-AI/LitServe#267]

**Comment by aniketmaurya** [comment]
Hi @ALEXuH, you can enable [batching](https://lightning.ai/docs/litserve/features/batching) to handle multiple requests in a batch. 

It would work as shown in the diagram below ([docs](https://lightning.ai/docs/litserve/features/batching)): 

![image](https://github.com/user-attachments/assets/1f4ea229-7282-4278-9952-612233b20260)

**Comment by ALEXuH** [comment]
I used this whisper to test（https://lightning.ai/lightning-ai/studios/deploy-a-real-time-voice-transcription-app?section=audio）, when I opened batch, the client received only one word, is the client also need to receive batch.

**Comment by aniketmaurya** [comment]
Client doesn't need to handle batching. Could you share a reproducible code here that you used for the batching server?

**Comment by aniketmaurya** [comment]
when you enable batching (add max_batch_size), you might have to change the `predict` method that receives the batched data and `encode_response` that will receive batched response.

**Comment by ALEXuH** [comment]
> when you enable batching (add max_batch_size), you might have to change the `predict` method that receives the batched data and `encode_response` that will receive batched response.

Thanks, how can I change it, can you give some advice,

**Comment by ALEXuH** [comment]
> when you enable batching (add max_batch_size), you might have to change the `predict` method that receives the batched data and `encode_response` that will receive batched response.

Thanks I know how it works
