### ISSUE TITLE
Supporting query params alongside file upload

### ISSUE THREAD

**Issue by energydrink9** [Lightning-AI/LitServe#272]
### ⚠️ BEFORE SUBMITTING, READ:

We're excited for your request! However, here are things we are not interested in:

- Decorators.
- Doing the same thing in multiple ways.    
- Adding more layers of abstraction... tree-depth should be 1 at most.
- Features that over-engineer or complicate the code internals.    
- Linters, and crud that complicates projects.    

----

## 🚀 Feature

Hello team,

Please correct me if I'm wrong but I couldn't find a way to specify query parameters for my endpoint when using a request annotated with FileUpload in `decode_request`. Is it possible to add support for them? 

### Motivation

It's sometimes useful to specify additional parameters in the request in order to control inference.

**Comment by aniketmaurya** [comment]
hi @energydrink9, you can send multiple data along with File upload as following:

### Server example 

```python
from PIL import Image
from fastapi import Request
import litserve as ls

class ImageAPI(ls.LitAPI):
    def setup(self, device):
        self.model = lambda x: x.size

    def decode_request(self, request: Request):
        print(request["model_name"])
        return Image.open(request["request"].filename)

    def predict(self, x):
        return self.model(x)

    def encode_response(self, output):
        return {"output": output}

if __name__ == "__main__":
    api = ImageAPI()
    server = ls.LitServer(api)
    server.run(port=8000)
```

### Client

```python
import requests

url = "http://127.0.0.1:8000/predict"
image_path = "image.jpg"

# Open the image file in binary mode
with open(image_path, 'rb') as image_file:
    files = {'request': image_file}
    response = requests.post(url, files=files, data={"model_name": "resnet50"})
print(response.json())
```

**Comment by aniketmaurya** [comment]
Added a new section for this in the documentation [here](https://lightning.ai/docs/litserve/features/request-response-format#upload-file-and-json-data). Please let me know if it helps!

**Comment by energydrink9** [comment]
Thank you Aniket, I managed to implement the parameterization following your advice
