### ISSUE TITLE
Add Support to Huggingface Diffusers!

### ISSUE THREAD

**Issue by KaifAhmad1** [Lightning-AI/LitServe#275]
Add real-time support for serving diffusion models via the Hugging Face `diffusers` library.
https://huggingface.co/docs/diffusers/en/index

**Comment by bhimrazy** [comment]
Hi @KaifAhmad1,  

Here is a studio template on how to deploy diffusion models using **litserve**: [Lightning AI - Deploy a private API for Stable Diffusion 2](https://lightning.ai/lightning-ai/studios/deploy-a-private-api-for-stable-diffusion-2).  

With **litserve**, you can easily deploy any model.

**Comment by aniketmaurya** [comment]
@KaifAhmad1, as mentioned by @bhimrazy you can serve any model with LitServe. Please feel free to reopen this issue if you still have questions.
