### ISSUE TITLE
Custom HTTPException Not Working as Expected

### ISSUE THREAD

**Issue by randydl** [Lightning-AI/LitServe#301]
When attempting to raise a custom HTTPException in the decode_request method, the expected behavior is not observed. Instead, the server responds with an internal server error (HTTP 500).

```python
def decode_request(self, request):
    raise HTTPException(status_code=400, detail='Test')
```

Expected Behavior:
The server should return a 400 Bad Request response with the detail message "Test".

Actual Behavior:
The server returns a 500 Internal Server Error with the following message:
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://127.0.0.1:8100/predict

**Comment by aniketmaurya** [comment]
hi @randydl, I am investigating this issue. In the meanwhile, I found that raising `raise HTTPException(400, 'Test')` works but the same with arguments doesn't. So for now you can try the following:

```py
def decode_request(self, request):
    raise HTTPException(400, 'Test')
```

**Comment by randydl** [comment]
Hi @aniketmaurya, Thank you so much for your answer. "raise HTTPException(400, 'Test')" works correctly.

**Comment by aniketmaurya** [comment]
Glad to know it worked @randydl!! Coming version of LitServe will be able to handle `HTTPException` with named arguments too.
