### ISSUE TITLE
Embedding model support with openai spec

### ISSUE THREAD

**Issue by riyajatar37003** [Lightning-AI/LitServe#305]
Hi,
can i do the own custom embedding model deployment with litserve.? any document on this

**Comment by grumpyp** [comment]
There's a great tutorial on how to do this from one of the maintainers @aniketmaurya 

https://lightning.ai/lightning-ai/studios/deploy-text-embedding-api-with-litserve

You'd basically just wrap the model in the `setup` method and could use it in the `predit` method.

```
import litserve as ls

**Comment by riyajatar37003** [comment]
its not opena ai compatible thats what i am looking

**Comment by riyajatar37003** [comment]
`from sentence_transformers import SentenceTransformer
import litserve as ls
class EmbeddingAPI(ls.LitAPI):
    def setup(self, device):
        self.instruction = "Represent this sentence for searching relevant passages: "
        self.model = SentenceTransformer('BAAI/bge-large-en-v1.5', device=device)

    def decode_request(self, request):
        return request["input"]

    def predict(self, query):
        return self.model.encode([self.instruction + query], normalize_embeddings=True)

    def encode_response(self, output):
        return {"embedding": output[0].tolist()}

if __name__ == "__main__":
    api = EmbeddingAPI()
    server = ls.LitServer(api,api_path='/embeddings')
    server.run(port=8000)
`


import litellm
import os

response = litellm.embedding(
    model="openai/mymodel",               # add `openai/` prefix to model so litellm knows to route to OpenAI
    api_key="No-key",                  # api key to your openai compatible endpoint
    api_base="http://127.0.0.1:8000",     # set API Base of your Custom OpenAI Endpoint
    input="good morning from litellm"
)
# print(response)

**Comment by bhimrazy** [comment]
Hi @riyajatar37003, this studio might be helpful for your use case: https://lightning.ai/bhimrajyadav/studios/deploy-openai-like-embedding-api-with-litserve-on-studios. 

> It also includes additional features like support for different models. Feel free to modify it to suit your needs.

**Comment by aniketmaurya** [comment]
@riyajatar37003 currently LitServe doesn't have inbuilt way to serve OpenAI compatible Embedding model. It can be implemented using the [OpenAISpec](https://github.com/Lightning-AI/LitServe/blob/4232377cde69713c1b9a222005614d56c16ded2d/src/litserve/specs/openai.py#L254) class. 

Would love to see a contribution if you are interested 😄

**Comment by Demirrr** [comment]
Stating that Litserve has the Open AI compatibility is **an overstatement** isn't it ? @aniketmaurya 

https://github.com/Lightning-AI/LitServe?tab=readme-ov-file#features
https://lightning.ai/docs/litserve/features/open-ai-spec#openai-api

vllm is a perfect example for the Open AI compatibility
https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html

**Comment by riyajatar37003** [comment]
Ya but does it support embedding

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by aniketmaurya** [comment]
@riyajatar37003 no, it doesn't -  https://github.com/Lightning-AI/LitServe/issues/305#issuecomment-2382891574

**Comment by aniketmaurya** [comment]
> Stating that Litserve has the Open AI compatibility is **an overstatement** isn't it ? @aniketmaurya
> 
> [Lightning-AI/LitServe#features](https://github.com/Lightning-AI/LitServe?tab=readme-ov-file#features) [lightning.ai/docs/litserve/features/open-ai-spec#openai-api](https://lightning.ai/docs/litserve/features/open-ai-spec#openai-api)
> 
> vllm is a perfect example for the Open AI compatibility [docs.vllm.ai/en/latest/serving/openai_compatible_server.html](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html)

@Demirrr don't see anything that you can do with vLLM and not with LitServe [OpenAISpec](https://lightning.ai/docs/litserve/features/open-ai-spec#use-openai-client). Maybe I might be missing something. What are you trying to do with LitServe and unable to do?

**Comment by Demirrr** [comment]
1. vLLM supports embedding models  and LitServe currently does not support as you have also pointed out it.
2. vLLM supports guided_choice option and few more usefull options (https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html#extra-parameters-for-completions-api), e.g., the following computation cannot be carried out in LitServe.

```python

completion = client.chat.completions.create(
  model="NousResearch/Meta-Llama-3-8B-Instruct",
  messages=[
    {"role": "user", "content": "Classify this sentiment: vLLM is wonderful!"}
  ],
  extra_body={
    "guided_choice": ["positive", "negative"]
  }
)
```
3. Autoscalling, Multi-machine inference, and Authentication features are **free in vllm**

Currently, I am unable to see the advantages of using LitServe over vllm. Yet, please correct me if  if any of the above written points are wrong.

**Comment by riyajatar37003** [comment]
Where do you see that vllm supports embedding models?

From: Caglar Demir ***@***.***>
Date: Tuesday, 1 October 2024 at 2:23 PM
To: Lightning-AI/LitServe ***@***.***>
Cc: Riyaj Atar ***@***.***>, Mention ***@***.***>
Subject: Re: [Lightning-AI/LitServe] Embedding model support with openai spec (Issue #305)
1.   [External Email]

________________________________
vLLM supports embedding models and LitServe currently does not support as you have also pointed out it.

  1.  vLLM supports guided_choice option and few more usefull options (https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html#extra-parameters-for-completions-api<https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html#extra-parameters-for-completions-api>), e.g., the following computation cannot be carried out in LitServe.

completion = client.chat.completions.create(

  model="NousResearch/Meta-Llama-3-8B-Instruct",

  messages=[

    {"role": "user", "content": "Classify this sentiment: vLLM is wonderful!"}

  ],

  extra_body={

    "guided_choice": ["positive", "negative"]

  }

)

  1.  Autoscalling, Multi-machine inference, and Authentication features are free in vllm

Currently, I am unable to see the advantages of using LitServe over vllm. Yet, please correct me if if any of the above written points are wrong.

**Comment by Demirrr** [comment]
https://github.com/vllm-project/vllm/blob/main/examples/offline_inference_embedding.py

**Comment by riyajatar37003** [comment]
Its offline , not similar to decoder model. Is my understanding correct?

From: Caglar Demir ***@***.***>
Date: Tuesday, 1 October 2024 at 2:28 PM
To: Lightning-AI/LitServe ***@***.***>
Cc: Riyaj Atar ***@***.***>, Mention ***@***.***>
Subject: Re: [Lightning-AI/LitServe] Embedding model support with openai spec (Issue #305)
[External Email]

________________________________
https://github.com/vllm-project/vllm/blob/main/examples/offline_inference_embedding.py @riyajatar37003<https://github.com/riyajatar37003>

**Comment by aniketmaurya** [comment]
@Demirrr LitServe is generic model serving library not only for LLMs.

At the moment, it provides `OpenAISpec` support for chat completion API only. To serve an embedding model with OpenAI API, you can use the [Pydantic input](https://lightning.ai/docs/litserve/features/request-response-format#pydantic-input) request to build a OpenAI compatible format. 

Other features like guided choice can also be implemented by customizing the [decode_method](https://lightning.ai/docs/litserve/features/open-ai-spec#override-decoderequest).

Autoscaling and authentication is free in LitServe too. Please feel free to refer to the docs (lightning.ai/litserve) and let us know if you have any feedback!
