### ISSUE TITLE
Pyright issues [Name mismatches]

### ISSUE THREAD

**Issue by grumpyp** [Lightning-AI/LitServe#310]
### Description

When creating a new notebook via Lightning and copying the example code from the README, Pyright shows issues with the abstract methods of the `LitAPI` base class.

The error occurs due to a parameter name mismatch in method overrides:

```
Method "setup" overrides class "LitAPI" in an incompatible manner Parameter 2 name mismatch: base parameter is named "devices", override parameter is named "device" Pyright[reportIncompatibleMethodOverride]
```

![image](https://github.com/user-attachments/assets/e8f21894-1dd0-47a7-acba-758149e5d22f)

### Steps to Reproduce

1. Open a new notebook in Lightning Studio.
2. Copy the example code from the README.
3. Observe the Pyright issues that appear for the `LitAPI` base class methods.

### Expected Behavior

No Pyright issues should be present. Although this won't block users, it can cause confusion, especially for those new to the framework.

### Environment

- Lightning Studio
- Pyright

### Additional Context

I’d be happy to work on resolving this issue (Updating the README should do the job?)

**Comment by aniketmaurya** [comment]
thanks for identifying the issue @grumpyp. If you are interested in contributing to this as well - you can rename the `devices` argument [here](https://github.com/Lightning-AI/LitServe/blob/830e4c0f0919195118b0c41529d2678023229aaf/src/litserve/api.py#L35) to `device`.

**Comment by Borda** [comment]
cc: @ethanwharris 🦩
