### ISSUE TITLE
Benchmarking gRPC with LitServe – Surprising Results

### ISSUE THREAD

**Issue by deependujha** [Lightning-AI/LitServe#323]
## Background

For the last week, I've been working on [Lightning Moshi](https://github.com/deependujha/Lightning-Moshi), a project that lets users to communicate with [Moshi (a 7.69 billion parameter speech-to-speech model)](https://github.com/kyutai-labs/moshi).

I  added gRPC support to LitServe in the hope that it would outperform the standard HTTP protocol, particularly in scenarios with high traffic or larger payloads. The idea was to let users easily switch between HTTP and gRPC when scaling or in production.

[output.webm](https://github.com/user-attachments/assets/ea702e10-acdf-4cb4-96c8-b3fdd304afea)

---

## Switching from HTTP to gRPC

- [LitServe with gRPC support code](https://github.com/deependujha/Lightning-Moshi/tree/main/LitServe_with_grpc)

1. Generate the proto file
```bash
litserve generate_protobuf
```
2. Modify the proto file according to your needs
3. Generate the python grpc server code (`litserve command helps`)
4. Just import in your litserve server and pass to the `LitServer` class
![litserve_grpc](https://github.com/user-attachments/assets/0c027021-eb67-4389-920e-d995e1c0da8f)

---

## Benchmarking Results: `HTTP vs gRPC`

To compare HTTP vs gRPC, I focused on payload transfer rather than the model itself. I created a Go client and a Python LitServe server for both protocols and **ran benchmarks across multiple cases**.

- Client was running in 'us-west-1' and server was running in 'us-east-1'.

Key findings:

- gRPC underperformed HTTP, especially for larger payloads, by up to 3x.
- When using JSON paylod, gRPC was comparable to HTTP, but it consistently lagged when it came to binary  (image, and audio) payloads.

---

### For simple `request-response`

- For a single field json `{"text": "hello"}`

![benchmark_results_http_simple_json csv-vs-benchmark_results_grpc_simple_json csv](https://github.com/user-attachments/assets/0432b7ba-69df-4a23-bc30-6370c6590a1b)

- For json with 5 fields

![benchmark_results_http_normal_json csv-vs-benchmark_results_grpc_normal_json csv](https://github.com/user-attachments/assets/945b6d05-f90a-4b8f-ae8e-d190839a384e)

- For json with 100 fields

![benchmark_results_http_big_json csv-vs-benchmark_results_grpc_big_json csv](https://github.com/user-attachments/assets/d9570f13-047c-40ed-9b10-fe2fd01d3eaa)

- for image `(grpc underperforms http by a lot)`

![benchmark_results_http_image csv-vs-benchmark_results_grpc_image csv](https://github.com/user-attachments/assets/01e05ee0-f874-41a8-8fcc-6266b5ebd0e8)

- for audio file `(almost 3x slower than http, god!)`

![benchmark_results_http_audio csv-vs-benchmark_results_grpc_audio csv](https://github.com/user-attachments/assets/7d4acd60-23ff-40ed-8bfd-0bb0cd9a83e3)

---

### For `streaming text` & `bytes`

- Streaming text

![benchmark_results_http_stream_text csv-vs-benchmark_results_grpc_stream_text csv](https://github.com/user-attachments/assets/32a82483-04f3-4128-81f8-5dfe7049162e)

- Streaming bytes

![benchmark_results_http_stream_bytes csv-vs-benchmark_results_grpc_stream_bytes csv](https://github.com/user-attachments/assets/2c728a16-41da-4094-99e9-7ea325a50ebb)

---

## Conclusion

Unfortunately, gRPC did not meet expectations in these benchmarks, underperforming in large payload cases by a significant margin. While gRPC excelled in some smaller use cases, its performance in others was suboptimal.

I’ve shared the benchmarking code [here](https://github.com/deependujha/Lightning-Moshi/tree/main/benchmark-litserve-grpc). Would love any feedback or thoughts on where I might improve my gRPC implementation!

**Comment by aniketmaurya** [comment]
thank you @deependujha for the effort to post your detailed findings here. For people referring to this for first time, there are some nice discussion about this on the [Lightning reddit channel here](https://www.reddit.com/r/lightningAI/comments/1fw472z/benchmarking_grpc_with_litserve_surprising_results/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) as well.
