### ISSUE TITLE
Litserve entrypoint wasn't properly registered on first install in Studios

### ISSUE THREAD

**Issue by tchaton** [Lightning-AI/LitServe#343]
### To Reproduce

Attach a [Lightning Studio](https://lightning.ai/studios) which is fully reproducible (code, dependencies, environment, etc...) to reproduce this:   

1. Create a [Studio](https://lightning.ai/studios).    
2. Reproduce the issue in the Studio.    
3. [Publish the Studio](https://lightning.ai/docs/overview/studios/publishing#how-to-publish).
4. Paste the Studio link here.    

![image](https://github.com/user-attachments/assets/471fbbec-f83e-4007-b29c-46f501b1b671)

I had to re-install the LitServe for it to work.

### Environment
If you published a Studio with your bug report, we can automatically get this information. Otherwise, please describe:   

- PyTorch/Jax/Tensorflow Version (e.g., 1.0):
- OS (e.g., Linux):
- How you installed PyTorch (`conda`, `pip`, source):
- Build command you used (if compiling from source):
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- Any other relevant information:

**Comment by aniketmaurya** [comment]
seems like the default is a version behind that's why it didn't work. I will upgrade that. thanks for reporting.
