### ISSUE TITLE
Add dockerize example in the README

### ISSUE THREAD

**Issue by tchaton** [Lightning-AI/LitServe#345]
----

### Motivation

Right now, there is no mention of docker within the README. We should have an explicit example on how to use it right after running the server.

**Comment by aniketmaurya** [comment]
We only keep the simple example on README. Rest all features could be found on the [docs](https://lightning.ai/docs/litserve/features/dockerization-deployment)

**Comment by tchaton** [comment]
Yes, this is too convoluted. IMO, docker should be there.
