### ISSUE TITLE
LitServe server doesn't crash when there is a failure in setup

### ISSUE THREAD

**Issue by tchaton** [Lightning-AI/LitServe#347]
### To Reproduce

Attach a [Lightning Studio](https://lightning.ai/studios) which is fully reproducible (code, dependencies, environment, etc...) to reproduce this:   

1. Create a [Studio](https://lightning.ai/studios).    
2. Reproduce the issue in the Studio.    
3. [Publish the Studio](https://lightning.ai/docs/overview/studios/publishing#how-to-publish).
4. Paste the Studio link here.    

```python
from litserve import LitAPI, LitServer

class DebugLitAPI(LitAPI):
    def setup(self, device):
        raise Exception

    def predict(self, inputs):
        return None

if __name__ == "__main__":
    api = DebugLitAPI()
    server = LitServer(api, accelerator='auto', devices='auto', workers_per_device=2)
    server.run(port=8000)
```

Instead, it should return exit code error 1.

### Environment
If you published a Studio with your bug report, we can automatically get this information. Otherwise, please describe:   

- PyTorch/Jax/Tensorflow Version (e.g., 1.0):
- OS (e.g., Linux):
- How you installed PyTorch (`conda`, `pip`, source):
- Build command you used (if compiling from source):
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- Any other relevant information:

**Comment by Borda** [comment]
seems to be the same as #293

**Comment by aniketmaurya** [comment]
sure go ahead @grumpyp!! we call `lit_api.setup` [here](https://github.com/Lightning-AI/LitServe/blob/23ba5e2386d34afaac77ec5881ef5f4959885a89/src/litserve/loops.py#L406). Probably we can do a check if the started workers successfully called setup or not [here](https://github.com/Lightning-AI/LitServe/blob/23ba5e2386d34afaac77ec5881ef5f4959885a89/src/litserve/server.py#L482).
