### ISSUE TITLE
Support for async requests or webhooks

### ISSUE THREAD

**Issue by brian316** [Lightning-AI/LitServe#348]
----

## 🚀 Feature

Is there currently a way to run inference and get the result by polling or a webhook callback? 

### Motivation

If an inference takes a long time to run lets say 30 min you dont want the connection to drop because you will have to rerun the inference especially on a shaky connection.

### Pitch

A webhook callback or polling method can let us run inference as a background task based off a uuid or something the user specifies so that they can come back at a later time for the result. can also help integrations so the inference is not a blocking request.

### Alternatives

[Cog](https://cog.run/http/#webhooks) from replicate implements a webhook

**Comment by brian316** [comment]
I've looked at the documentation and saw those handy Hooks, but wouldn't the the initial api request wait until the server returns something? I was thinking of returning something immediately like an id the user can poll for the polling method or for the web hook method return a success message. while still running the background task. I guess something that could potentially work is returning immediately in the predict function and run some thread in the background but that seems hacky to get it to work. having async task is important for my type of tasks

**Comment by aniketmaurya** [comment]
Yes @brian316  as you said, you can have a background thread execute the task and post the result back. But honestly LitServe focuses on model serving with high throughput and scale so we won't be taking this at this time unless we see a lot of demand for this request from the community. 

I really like this idea though and thank you for opening the issue.
