### ISSUE TITLE
Can't start the demo example without bug

### ISSUE THREAD

**Issue by anonym-ai** [Lightning-AI/LitServe#350]
## 🐛 Bug

Can't start a server with provided example code without error:
1. Address already in used while the port wasn't used before starting server
2. server is unhealthy

#### Code sample
```
import litserve as ls


class SimpleLitAPI(ls.LitAPI):
    # Called once at startup. Setup models, DB connections, etc...
    def setup(self, device):
        self.model = lambda x: x**2

    # Convert the request payload to model input.
    def decode_request(self, request):
        return request["input"]

    # Run inference on the the model, return the output.
    def predict(self, x):
        return self.model(x)

    # Convert the model output to a response payload.
    def encode_response(self, output):
        return {"output": output}


# LitServe scales your API!
api = SimpleLitAPI()
server = ls.LitServer(api)
server.run(port=18000)
```

#### Logs
⏚ [me:~/Gits/litserve_poc] master(+1/-1)* 10s ± python server.py 
INFO:     Uvicorn running on http://0.0.0.0:18000 (Press CTRL+C to quit)
Swagger UI is available at http://0.0.0.0:18000/docs
INFO:     Started server process [198772]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] Address already in use
INFO:     127.0.0.1:45704 - "GET /docs HTTP/1.1" 200 OK
INFO:     127.0.0.1:45704 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:45720 - "GET /health HTTP/1.1" 503 Service Unavailable
INFO:     127.0.0.1:56098 - "POST /predict HTTP/1.1" 500 Internal Server Error
...
    raise KeyError(key)
KeyError: 'Content-Type'

I used swagger for the /health and /predict. so swagger is working on 18000 port

when i do:
curl -X 'POST'   'http://0.0.0.0:18000/predict'   -H 'accept: application/json'   -d '{"input": 2}'

It just hangs and do nothing

### Expected behavior

1. Should be healthy
2. Should not hang on curl
3. Should respond to swager without error

### Environment
⏚ [me:~] $ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"

Python 3.11.0

⏚ [me:~/Gits/litserve_poc] master(+1/-1)* ± pip list
Package                  Version
------------------------ -----------
annotated-types          0.7.0
anyio                    4.6.2.post1
certifi                  2024.8.30
click                    8.1.7
fastapi                  0.115.4
filelock                 3.16.1
fsspec                   2024.10.0
h11                      0.14.0
httpcore                 1.0.6
httptools                0.6.4
httpx                    0.27.2
idna                     3.10
Jinja2                   3.1.4
litserve                 0.2.3
MarkupSafe               3.0.2
mpmath                   1.3.0
networkx                 3.4.2
numpy                    1.26.4
nvidia-cublas-cu12       12.4.5.8
nvidia-cuda-cupti-cu12   12.4.127
nvidia-cuda-nvrtc-cu12   12.4.127
nvidia-cuda-runtime-cu12 12.4.127
nvidia-cudnn-cu12        9.1.0.70
nvidia-cufft-cu12        11.2.1.3
nvidia-curand-cu12       10.3.5.147
nvidia-cusolver-cu12     11.6.1.9
nvidia-cusparse-cu12     12.3.1.170
nvidia-nccl-cu12         2.21.5
nvidia-nvjitlink-cu12    12.4.127
nvidia-nvtx-cu12         12.4.127
pip                      22.3
pydantic                 2.9.2
pydantic_core            2.23.4
python-dotenv            1.0.1
python-multipart         0.0.16
PyYAML                   6.0.2
setuptools               65.5.0
sniffio                  1.3.1
starlette                0.41.2
sympy                    1.13.1
torch                    2.5.0
triton                   3.1.0
typing_extensions        4.12.2
uvicorn                  0.32.0
uvloop                   0.21.0
watchfiles               0.24.0
websockets               13.1

[notice] A new release of pip available: 22.3 -> 24.3.1
[notice] To update, run: pip install --upgrade pip

**Comment by aniketmaurya** [comment]
@anonym-ai can you please guard the `server.run` with `if __name__ == "__main__":`. LitServe creates processes for inference worker. 

Let me know if this works - 
```python
import litserve as ls


class SimpleLitAPI(ls.LitAPI):
    # Called once at startup. Setup models, DB connections, etc...
    def setup(self, device):
        self.model = lambda x: x ** 2

    # Convert the request payload to model input.
    def decode_request(self, request):
        return request["input"]

    # Run inference on the the model, return the output.
    def predict(self, x):
        return self.model(x)

    # Convert the model output to a response payload.
    def encode_response(self, output):
        return {"output": output}


if __name__ == "__main__":
    # LitServe scales your API!
    api = SimpleLitAPI()
    server = ls.LitServer(api)
    server.run(port=18000)
```

**Comment by grumpyp** [comment]
I guess the `curl` is wrong.

Try this:

`curl -X POST http://127.0.0.1:8000/predict -H "Content-Type: application/json" -d '{"input": 4.0}'`

**Comment by anonym-ai** [comment]
Thanks to both of you for the fast and exact response @grumpyp  and @aniketmaurya.
It works. I close the issue
