### ISSUE TITLE
How to route /docs path in litserve behind a proxy?

### ISSUE THREAD

**Issue by Mayurji** [Lightning-AI/LitServe#352]
I have hosted litserve as kubernetes(EKS) deployment with a service, now it is further connected to a proxy with Virtual service CRD and gateway.

In eks deployment,

- Model: the url works 0.0.0.0:4000/predict after port forwarding.

- Docs: The url works 0.0.0.0:4000/docs after port forwarding.

In EKS Service, the above url works, mapping 4000:4000, and then port forwarding.

Now, Istio's virtual service has prefix set as "modV1" and I am able to hit the model api as

`domain-name/modV1/predict`

But /docs api doesn't work from virtual service,

`domain-name/modV1/docs`

How to update or direct the /docs route in litserve for proxy?

**Comment by Mayurji** [comment]
@aniketmaurya , We have seen similar issues happening with Fastapi, which is also the backend for litserve. But it seems like, in fastapi they are able to update the root_path as mentioned in the below url. Can we update root_path for litserve as well.

URL: https://stackoverflow.com/questions/78649231/fastapi-fetch-error-failed-to-load-openapi-json-404-error-when-deployed-in

**Comment by aniketmaurya** [comment]
> @aniketmaurya , We have seen similar issues happening with Fastapi, which is also the backend for litserve. But it seems like, in fastapi they are able to update the root_path as mentioned in the below url. Can we update root_path for litserve as well.
> 
> URL: https://stackoverflow.com/questions/78649231/fastapi-fetch-error-failed-to-load-openapi-json-404-error-when-deployed-in

All the APIs by default starts with root path "/", are you able to set that to your proxy?

**Comment by aniketmaurya** [comment]
hi @Mayurji, `/docs` is supposed to be used only for development so unfortunately we will not be prioritizing this at the moment.

**Comment by bhimrazy** [comment]
A somewhat similar issue: https://github.com/Lightning-AI/LitServe/issues/270

**Comment by michaeltinsley** [comment]
Posting here for anyone else that wants this functionality. 

I was able to get this working by setting the root path on the underlying FastAPI App object:

```python
if __name__ == "__main__":
    api = SimpleLitAPI()
    server = ls.LitServer(api, accelerator="auto")
    server.app.root_path = "/my-endpoint"
    server.run(port=8000)
```
I've not noticed any issues doing this so far
