### ISSUE TITLE
GET Request

### ISSUE THREAD

**Issue by gururaser** [Lightning-AI/LitServe#355]
----

### Motivation

I want to use LitServe for the search engine endpoint, so it would be nice to be able to send a GET request

### Pitch

I plan to use LitServe to create an embedding from the query entered and search it in the vector database. But I can't see how to make any GET endpoint. It seems that there is only POST at the moment.

**Comment by aniketmaurya** [comment]
Hi @gururaser, you can use the POST request to accept the query and perform vector search. GET requests has [limitations](https://www.w3schools.com/tags/ref_httpmethods.asp) and POST should be used in such cases.

**Comment by gururaser** [comment]
> Hi @gururaser, you can use the POST request to accept the query and perform vector search. GET requests has [limitations](https://www.w3schools.com/tags/ref_httpmethods.asp) and POST should be used in such cases.
> 
> Here is the docs for managing request-response with LitServe - https://lightning.ai/docs/litserve/features/request-response-format

Hello, I've already done demo with POST request. But I feel like GET requests are used in search endpoints in websites. For example, when I search on any e-commerce site, I notice that the GET request is used from the link of the site

**Comment by aniketmaurya** [comment]
@gururaser usually in production when serving the model, the server is put behind an UI or it's used as an API by another backend service. So, users shouldn't be directly talking to server. May I know how you're serving the model?

**Comment by aniketmaurya** [comment]
When users search in the input box, you can still send the text to LitServe endpoint using a POST request and return the response to the frontend.
