### ISSUE TITLE
bug: OpenAI-Spec should send text/event-stream

### ISSUE THREAD

**Issue by fabigr8** [Lightning-AI/LitServe#359]
## 🐛 Bug: OpenAI API-spec not using text/event-stream

LitServe implementation for `spec=ls.OpenAISpec()` when `stream=True`  wrongly responds with  `application/x-ndjson` as content-type. Altough the OpenAI python client lib can process such answers, its not their current standard, and therefore not supported from other third-party libraries. This causes other applications and libraries, that could otherwise naturally interact with LitServe, to crash or causes connection issues. 

I had exactly this issue when hosting a LLM via LitServe and trying to connect to it with [Open WebUI](https://github.com/open-webui/open-webui). This would most certainly be a showstopper for using litserve for me, and probably many others too. 

**Solution:** OpenAI implements its API to answer with `text/event-stream; charset=utf-8`, so should LitServe when using `spec=ls.OpenAISpec()` and `stream=True`.

### To Reproduce

- [x] Studio-Link: [Studio-with-Bug](https://lightning.ai/gwinnerf/studios/showing-bug-for-github-issue)
- [X] Reproduce the issue in the Studio.
- [X] Report the issue in the studio

The litserve studio has a server and client script, the client script consists of a streaming test and a content-type-test. You can use the same to check openAI's API. Just to compare, here are two test results as screenshots, the first showing results from LitServe-API, the second from OpenAI's chatGPT-API.

Litserve test result: 
![Screenshot from 2024-11-10 18-24-43](https://github.com/user-attachments/assets/27558c4a-1467-4a94-936d-654c9b26ce05)

OpenAI ChatGPT-API test result:
![Screenshot from 2024-11-10 18-35-02](https://github.com/user-attachments/assets/a06ca0cd-4e87-46f3-8742-7ba4fa54170f)

#### Code sample

Here is my minimal LitServe Server implementation:
```
import litserve as ls
from fastapi import Depends
from threading import Thread
from datetime import datetime

from typing import Annotated, AsyncGenerator, Dict, Iterator, List, Literal, Optional, Union
from litserve.specs.openai import ChatCompletionRequest, ChatMessage, ChatMessage, Function, Tool

import time


class LlamaIndexAPI(ls.LitAPI):
    def setup(self, device):
        #self.llm = None
        print("position 0")
    
    def predict(self, messages, context):
        # simple example of a generator that yields tokens from a fix text
        delay = 0.1  # seconds
        for token in """OpenAI is an American artificial intelligence (AI) research organization 
                        founded in December 2015 and headquartered in San Francisco, California. 
                        Its mission is to develop safe and beneficial artificial general intelligence 
                        (AGI), which it defines as highly autonomous systems that outperform humans 
                        at most economically valuable work.""".split():
            yield token + " "
            time.sleep(delay) #just to simulate a slower stream, otherwise answers come in one block

# main function to start server 
if __name__ == "__main__":
    api = LlamaIndexAPI()
    server = ls.LitServer(api, spec=ls.OpenAISpec(), stream=True) 
    server.run(port=9000)

```

and here is a client code to test the mime/content-type:

```
import requests
from openai import OpenAI #pip install openai


def test_streaming_oai(base_url, api_key, model):
    
    # create client
    client = OpenAI(
        base_url=base_url,  # Specify your LitServe endpoint
        api_key=api_key,  # The API key is required, but it can be a placeholder in this context
    )

    # Create a chat completion request
    response = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": "Could you please count to 7? separate the numbers with a comma. E.g., 1, 2, 3 ..."},
        ],
        stream=True,
        temperature=0,
    )
    print("got a response")
    print(response)
    # create variables to collect the stream of chunks
    collected_chunks = []
    collected_messages = []
    # iterate through the stream of events
    for chunk in response:
        print("*****************")
        collected_chunks.append(chunk)  # save the event response
        chunk_message = chunk.choices[0].delta.content
        collected_messages.append(chunk_message)  # save the message
        #print(f"Message received: {chunk_message}")  # print the delay and text
        print(chunk)
    
    #print collected_chunks
    print("*****************")
    print(f"Full Message collected by client: {collected_messages}")
    #print collected_messages
    print("*****************")
    print(f"Response object received:\n{response}")


def test_streaming_mimetype(base_url, api_key, model):
    url = base_url + "/chat/completions"
    headers = {
        "Authorization": api_key,
        "Content-Type": "application/json"
    }
    data = {
        "model": model,
        "messages": [
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": "Could you please count to 7? separate the numbers with a comma. E.g., 1, 2, 3 ..."}
        ],
        "stream": True
    }

    response = requests.post(url, headers=headers, json=data)

    #check meme-type / Content-Type
    if response.headers['Content-Type'] == "application/json":
        print(f"wrong content-type: {response.headers['Content-Type']}")

    elif response.headers['Content-Type'] ==  "application/x-ndjson":
        print(f"wrong content-type: {response.headers['Content-Type']}")

    elif response.headers['Content-Type'] ==  "text/event-stream; charset=utf-8":
        print(f"Correct Content type: {response.headers['Content-Type']}")

    else:
        print(f"UNKNOWN Content type: {response.headers['Content-Type']}")
    
    #finsih

if __name__ == "__main__":

    # server settings
    url = "http://localhost:9000/v1"
    api_key = "lit"
    model = "lit"
    # ##### Test General Streaming abbility 
    print(" ")
    print("#### Testing Streaming ####")
    test_streaming_oai(url, api_key, model)

    # ##### Test format
    print(" ")
    print("#### Testing Content-Type ####")
    test_streaming_mimetype(url, api_key, model)

    #finished
    print(" ")
    print("#### all tests finished ####")

```

### Expected behavior

LitServe should in case of `spec=ls.OpenAISpec()` and `stream=True` use `text/event-stream`  as server-sent events format, as done by openAI.

### Environment

See Studio for details. locally i used:
- OS: Linux
- Python version: 3.10
- current versions of litserve and opeAI packages.

**Comment by fabigr8** [comment]
I already have   _**fix**_   for that issue and created a branch as well. Let me know if its okay to create a PR for my fix, so you can revise my code; or if you instead want to fix it yourself.

PS: I tested the fix with my provided example above because I was having issues with the existing test scripts in the repo. It seems that most of the existing tests **import litserve** from the python path instead of using the local code of the cloned repo. Or how do you make sure that the local changes are pulled into the test?

**Comment by bhimrazy** [comment]
Interesting. It would be worth testing for vercel’s ai package as well.
https://github.com/vercel/ai

**Comment by aniketmaurya** [comment]
hi @fabigr8, that's a great catch! Please feel free to create the PR.

Tests are written with PyTest, you can install LitServe in editable mode (`pip install -e .`) and try running the test locally.

**Comment by bhimrazy** [comment]
@fabigr8, it sounds like you’ll need to work with a fork. Here’s how you can proceed:
	1.	Create a fork of the repository.
	2.	In your forked repository, create a new branch and add all your changes.
	3.	Open a pull request from your branch to the main branch of the upstream repository.
