### ISSUE TITLE
Info route

### ISSUE THREAD

**Issue by lorenzomassimiani** [Lightning-AI/LitServe#366]
----

## 🚀 Feature

Add a `/info` route that returns 

- Litserver configuration
- Model metadata

for example:
```
{
  "model": {
    "name": "my-awesome-model",
    "version": "v1.1.0"
  },
  "litserver": {
    "num_workers": 2,
    "devices": ["cpu"],
    "workers_per_device": 2,
    "max_batch_size": 4,
    "batch_timeout": "100ms"
  }
}
```

### Motivation

It is useful to have a fast way to investigate server and loaded model configuration, for example a backend could call this api to show in a dedicated UI what model is currently deployed in production.

### Pitch

Model metadata will be passed to `LitServer` class as a custom JSON serializable object:

```
server = ls.LitServer(ExampleLitAPI(), model_metadata={"name": "my-awesome-model", "version": "v1.1.0"})
```

then in the method `register_endpoint` the route will be added to the fastapi app.

**Comment by williamFalcon** [comment]
@lorenzomassimiani this looks good. submit a PR (cc @aniketmaurya )

**Comment by lorenzomassimiani** [comment]
good, I'll work on this in the next days!
