### ISSUE TITLE
Only enable either `predict` or `stream-predict` API based on `stream` argument to LitServer

### ISSUE THREAD

**Issue by aniketmaurya** [Lightning-AI/LitServe#47]
LitServe uses `/predict` for regular and `/stream-predict` endpoint path with streaming mode. 

We should only register either of these to FastAPI endpoint route or alternatively maybe just use `/predict` path for both the tasks by passing the relevant API function.

<img width="1509" alt="image" src="https://github.com/Lightning-AI/litserve/assets/21018714/daf062e2-d9b6-43a7-95ca-4e723ee8ad6d">

### To Reproduce

Run a server `LitServer(..., stream=True)` flag

**Comment by aniketmaurya** [comment]
#76 should close this

**Comment by lantiga** [comment]
Closed by #93
