### ISSUE TITLE
Add a detached mode

### ISSUE THREAD

**Issue by rasbt** [Lightning-AI/LitServe#56]
## 🚀 Feature

It would be nice to add a `--detach` mode similar to `jekyll serve` to detach the session.

### Motivation

This could be useful for testing purposes and usability etc so it doesn't block the main terminal.

### Pitch

The equivalent of

```
jekyll serve --detach
...
      Generating... 
                    done in 3.982 seconds.
 Auto-regeneration: disabled when running server detached.
    Server address: http://127.0.0.1:4000/
Server detached with pid '76023'. Run `pkill -f jekyll' or `kill -9 76023' to stop the server.
```

**Comment by williamFalcon** [comment]
this would require introducing a CLI which may not be a bad idea

**Comment by andyland** [comment]
You can just put an ampersand at the end to achieve the same thing

```sh
⚡ ~ python server.py &
[1] 6372
```

**Comment by aniketmaurya** [comment]
that's right! as Andy said you can put ampersand for this. But to terminate the server you either have to note down the process id and kill that or find it later and kill it. Which might be intimidating for some users.
