### ISSUE TITLE
Running litserve with HTTPS

### ISSUE THREAD

**Issue by BZandi** [Lightning-AI/litserve#58]
Thanks for this great project! I’m currently exploring litserve and I’m curious whether it supports HTTPS encryption for communication, similar to what uvicorn offers:

```shell
$ uvicorn main:app --ssl-keyfile=./key.pem --ssl-certfile=./cert.pem
```

**Comment by aniketmaurya** [comment]
hi @BZandi! Yes since LitServe is based on FastAPI, you can provide these arguments to the `LitServe.run` method. 

<img width="1330" alt="image" src="https://github.com/Lightning-AI/litserve/assets/21018714/55ac18ab-5dea-47f6-b5a4-5aa83ed908ae">

**Comment by aniketmaurya** [comment]
hi @BZandi, were you able to enable HTTPS encryption with LitServe similar to uvicorn? If yes, please feel free to close the issue.
