### ISSUE TITLE
end-to-end tests

### ISSUE THREAD

**Issue by aniketmaurya** [Lightning-AI/LitServe#67]
Add end-to-end tests for:

- [x] **dynamic Batching** - addressed by #68 
- [x] **Dynamic batching with streaming** - addressed by #68 
- [x] single prediction #70
- [x] single streaming #247

**Comment by imsiddhant07** [comment]
Hi @aniketmaurya wanted to confirm the scope of contribution here. 

With reference to
> Dynamic batching with streaming - addressed by https://github.com/Lightning-AI/LitServe/pull/68

I can see there was _unbatch_no_stream() unbatch() methods added to LitAPI() along with tests.

Is a similar contribution expected for single streaming as well, i.e. methods in LitAPI class as well as tests under e2e.

**Comment by AdolfoVillalobos** [comment]
Hello! I submitted #247 to handle a single streaming case. I hope I understood the case correctly. Let me know If I got something wrong please ;)
