### ISSUE TITLE
test_timeout test is flaky

### ISSUE THREAD

**Issue by aniketmaurya** [Lightning-AI/LitServe#71]
### To Reproduce

1. Run '....'
1. Scroll down to '....'
1. See error

### Environment

- PyTorch Version (e.g., 1.0):
- OS (e.g., Linux):
- How you installed PyTorch (`conda`, `pip`, source):
- Build command you used (if compiling from source):
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- Any other relevant information:

**Comment by lantiga** [comment]
Is it just for win?

**Comment by aniketmaurya** [comment]
yes @lantiga, sometimes the timeout test fails because of slow speed.

**Comment by aniketmaurya** [comment]
closing since haven't noticed this issue after creating the issue.
